### ISSUE TITLE
SqsListener String index out of bounds issue

### ISSUE THREAD

**Issue by DPetrunov** [spring-cloud/spring-cloud-aws#374]
I'm encountering a problem when trying to use the @SQSListener annotation from the Spring Cloud module. My Listener method is defined as follows:
```
@SqsListener(value = "myproject-dev-au-error-queue")
public void listenPhoenix(String message) throws IOException {

    logger.info(message);
 }

```
And when I start receiving messages from the queue i get the following stack trace:

```
Exception in thread "simpleMessageListenerContainer-4" Exception in thread "simpleMessageListenerContainer-6" Exception in thread "simpleMessageListenerContainer-9" Exception in thread "simpleMessageListenerContainer-10" java.lang.StringIndexOutOfBoundsException: String index out of range: -1
    at java.lang.String.substring(String.java:1931)
    at org.springframework.cloud.aws.messaging.core.QueueMessageUtils.getNumberValue(QueueMessageUtils.java:93)
    at org.springframework.cloud.aws.messaging.core.QueueMessageUtils.getMessageAttributesAsMessageHeaders(QueueMessageUtils.java:80)
    at org.springframework.cloud.aws.messaging.core.QueueMessageUtils.createMessage(QueueMessageUtils.java:56)
    at org.springframework.cloud.aws.messaging.listener.SimpleMessageListenerContainer$MessageExecutor.getMessageForExecution(SimpleMessageListenerContainer.java:375)
    at org.springframework.cloud.aws.messaging.listener.SimpleMessageListenerContainer$MessageExecutor.run(SimpleMessageListenerContainer.java:336)
    at org.springframework.cloud.aws.messaging.listener.SimpleMessageListenerContainer$SignalExecutingRunnable.run(SimpleMessageListenerContainer.java:392)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```

With the problem being in QueueMessageUtils.getNumberValue(...), more specifically

```
private static Object getNumberValue(MessageAttributeValue value) {
    String numberType = value.getDataType().substring("Number".length() + 1);
    ....
}
```
This is happening on all versions of Spring Cloud (Dalston, Finchley, Edgeware, etc.)

Any ideas on what might be causing this behaviour?

**Comment by kevinhwang** [comment]
Also having this issue. Seems the issue is here:
https://github.com/spring-cloud/spring-cloud-aws/blob/64ec6d15c67e98c3372ab88c9e5b31d5a89a68f8/spring-cloud-aws-messaging/src/main/java/org/springframework/cloud/aws/messaging/core/QueueMessageUtils.java#L92-L101

`spring-cloud-aws` expects numbers in SQS message attributes to have a typename of `Number.${JAVA_TYPE_NAME}`, e.g., `Number.java.lang.Integer`. This is definitely not part of the AWS SQS interface, and is a bug and should be fixed.

**Comment by richcoto** [comment]
Hi I'm having this issue, so i go and download to my project Finchley.SR3 which is on december, i thought that version was going to have this fix, in which version of maven dependency i can find this fix you're applying here ?

**Comment by DavidFHarty** [comment]
Any update on this? We are closing in on a year since first reported

**Comment by FedorRomanov** [comment]
Any progress on this issue? It would be good to fix it

**Comment by youngkjun** [comment]
Any update on this bug? There's still the same issue in the latest version.

**Comment by mkatircioglu** [comment]
Hi @DPetrunov @youngkjun FedorRomanov . I can not reproduce the bug with spring-boot-starter-parent:2.3.1.RELEASE and spring-cloud-dependencies:Hoxton.SR5. Do you still encounter this issue?

**Comment by DPetrunov** [comment]
@mkatircioglu , Please take a look at @kevinhwang's comment

**Comment by maciejwalkowiak** [comment]
@DPetrunov the issue is fixed and will be released in 2.3.

**Comment by fblanke** [comment]
@maciejwalkowiak Any idea when 2.3 will be released?

**Comment by maciejwalkowiak** [comment]
I can't tell exact date as there are quite a few factors related to this release - like changing Maven coordinates - but I can tell for sure that it's not going to happen in next 2-3 weeks.

**Comment by smoomrik** [comment]
@maciejwalkowiak is it visible now when it will be released? Is it possible to fastrack that as 2.2.4?

**Comment by cvwjensen** [comment]
I can confirm to have the same issue in spring-cloud-aws-messaging-2.2.4.RELEASE.jar which ships with Hoxton.SR8

**Comment by cvwjensen** [comment]
It seems the problem have been fixed on master: https://github.com/spring-cloud/spring-cloud-aws/blob/master/spring-cloud-aws-messaging/src/main/java/org/springframework/cloud/aws/messaging/core/QueueMessageUtils.java. When will this version be released?

**Comment by maciejwalkowiak** [comment]
Spring Cloud AWS 2.3 has been released in March https://spring.io/blog/2021/03/17/spring-cloud-aws-2-3-is-now-available
